language: node_js
node_js: stable
before_install:
  - export TZ='Asia/Shanghai'
install:
  - npm install
script:
  - hexo clean
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "kinegratii"
  - git config user.email "kinegratii@gmail.com"
  - git add .
  - git commit -m "update by Travis-CI at $(date '+%Y-%m-%d %H:%M:%S')"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
branches:
  only:
  - hexo
env:
  global:
    - GH_REF: github.com/kinegratii/kinegratii.github.io.git
